[package]
name = "reqwest"
version = "0.10.0-alpha.0" # remember to update html_root_url
description = "higher level HTTP client library"
keywords = ["http", "request", "client"]
repository = "https://github.com/seanmonstar/reqwest"
documentation = "https://docs.rs/reqwest"
authors = ["Sean McArthur <sean@seanmonstar.com>"]
readme = "README.md"
license = "MIT/Apache-2.0"
categories = ["web-programming::http-client"]
edition = "2018"

publish = false

[package.metadata.docs.rs]
all-features = true

[dependencies]
base64 = "0.10"
bytes = "0.4"
encoding_rs = "0.8"
futures-preview = { version = "0.3.0-alpha.18", features = ["async-await", "compat", "io-compat", "nightly"] }
http = "0.1.15"
hyper = { git = "https://github.com/hyperium/hyper.git", branch = "master" }
flate2 = { version = "^1.0.7", default-features = false, features = ["rust_backend"] }
log = "0.4"
mime = "0.3.7"
mime_guess = "2.0"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5"
tokio = { version = "0.2.0-alpha.4", default-features = false, features = ["rt-full", "tcp"] }
url = "1.2"
uuid = { version = "0.7", features = ["v4"] }

# Optional deps...

#hyper-old-types = { git = "https://github.com/hyperium/hyper.git", branch = "master", optional = true, features = ["compat"] }
hyper-rustls = { git = "https://github.com/dbcfd/hyper-rustls.git", branch = "futures", optional = true }
hyper-tls = { git = "https://github.com/dbcfd/hyper-tls.git", branch = "tokio-alpha4", optional = true }
native-tls = { version = "0.2", optional = true }
rustls = { version = "0.16", features = ["dangerous_configuration"], optional = true }
socks = { version = "0.3.2", optional = true }
tokio-tls = { version = "0.3.0-alpha.4", optional = true }
tokio-rustls = { version = "0.12.0-alpha.1", optional = true }
trust-dns-resolver = { version = "0.11", optional = true }
webpki-roots = { version = "0.17", optional = true }
cookie_store = "0.7.0"
cookie = "0.12.0"
time = "0.1.42"

[dev-dependencies]
env_logger = "0.6"
failure = "0.1"
failure_derive = "0.1"
serde = { version = "1.0", features = ["derive"] }
libflate = "0.1"
doc-comment = "0.3"
bytes = "0.4"
tokio-fs = { version = "0.2.0-alpha.4" }

[features]
default = ["default-tls"]

tls = []

default-tls = ["hyper-tls", "native-tls", "tls", "tokio-tls"]
default-tls-vendored = ["default-tls", "native-tls/vendored"]

rustls-tls = ["hyper-rustls", "tokio-rustls", "webpki-roots", "rustls", "tls"]

trust-dns = ["trust-dns-resolver"]

[target.'cfg(windows)'.dependencies]
winreg = "0.6"
